/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vladimir.loshchin;

import java.util.List;

public class App {

    public static void main(String[] args) {
        int counter = args.length > 0 ? Integer.valueOf(args[0]) : 1;

        while (counter > 0) {
            try {
                List<Ticket> tickets = new StripBuilder().build();

                tickets.forEach(t -> {
                    System.out.println(t.toString());
                });

                counter--;
            } catch (IllegalStateException ex) {
                // System.err.println("Skip failed build");
            }
        }
    }
}
